// src/components/admins/students/ImportStudentsModal.tsx
import { useState } from "react";
import { X } from "lucide-react";
import { toast } from "react-toastify";
import Papa from "papaparse";
import { useCenterStore } from "@/stores/useCenterStore";
import { useStudentListStore } from "@/stores/useStudentListStore";
import { runWithConcurrency } from "@/utils/concurrency";
import { useOnlineStatus } from "@/hooks/useOnlineStatus";
import { useFacilitatorStore } from "@/stores/useFacilitatorStore";

interface ImportPreviewRow {
  firstName: string;
  middleName?: string | null;
  lastName: string;
  idNumber: string;
  password: string;
  currentCenter: number | null;
  isAutoGenerated: boolean;
}

interface ImportStudentsModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess?: () => void;
}

export default function ImportStudentsModal({
  isOpen,
  onClose,
  onSuccess,
}: ImportStudentsModalProps) {
  // ── Store
  const { centers } = useCenterStore();
  const { addStudent } = useStudentListStore();
  const online = useOnlineStatus();
  const isFacilitator = !!useFacilitatorStore.getState().currentFacilitator;
  // ── State
  const [csvPreview, setCsvPreview] = useState<{
    valid: ImportPreviewRow[];
    invalid: Array<{ row: number; reason: string }>;
  }>({ valid: [], invalid: [] });
  const [isImporting, setIsImporting] = useState(false);

  // ── Helper
  const generatePassword = () =>
    String(Math.floor(10000 + Math.random() * 90000));

  // ── Handlers: CSV upload & parsing
  const handleCSVUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (file.size > 1024 * 1024) {
      toast.error("CSV file must be under 1MB.");
      e.target.value = "";
      return;
    }

    if (!file.name.endsWith(".csv") && file.type !== "text/csv") {
      toast.error("Please upload a valid CSV file.");
      e.target.value = "";
      return;
    }

    const { students: existingStudents } = useStudentListStore.getState();
    const existingIds = new Set(existingStudents.map((s) => s.idNumber));
    const seenInFile = new Set<string>();

    Papa.parse(file, {
      header: true,
      skipEmptyLines: true,
      complete: (results) => {
        const valid: ImportPreviewRow[] = [];
        const invalid: Array<{ row: number; reason: string }> = [];

        results.data.forEach((row: any, index: number) => {
          const rowNum = index + 2;

          if (!row.firstName?.trim()) {
            invalid.push({ row: rowNum, reason: "Missing first name" });
            return;
          }
          if (!row.lastName?.trim()) {
            invalid.push({ row: rowNum, reason: "Missing last name" });
            return;
          }
          if (!row.idNumber?.trim()) {
            invalid.push({ row: rowNum, reason: "Missing ID number" });
            return;
          }
          if (!/^\d{2}-\d{4}-\d{2}$/.test(row.idNumber.trim())) {
            invalid.push({
              row: rowNum,
              reason: `Invalid ID format: ${row.idNumber}`,
            });
            return;
          }

          const trimmedIdNumber = row.idNumber.trim();
          if (existingIds.has(trimmedIdNumber)) {
            invalid.push({
              row: rowNum,
              reason: `ID Number already exists: ${trimmedIdNumber}`,
            });
            return;
          }
          if (seenInFile.has(trimmedIdNumber)) {
            invalid.push({
              row: rowNum,
              reason: `Duplicate ID Number within this file: ${trimmedIdNumber}`,
            });
            return;
          }
          seenInFile.add(trimmedIdNumber);

          const center = row.center?.trim()
            ? centers.find(
                (c) =>
                  c.title.toLowerCase() === row.center.trim().toLowerCase(),
              )
            : null;

          if (isFacilitator && !center) {
            invalid.push({
              row: rowNum,
              reason: row.center?.trim()
                ? `Center "${row.center.trim()}" not found or not assigned to you`
                : "Missing center (required for facilitators)",
            });
            return;
          }

          const password =
            row.password?.trim() && /^\d{5}$/.test(row.password.trim())
              ? row.password.trim()
              : generatePassword();

          valid.push({
            firstName: row.firstName.trim(),
            middleName: row.middleName?.trim() || null,
            lastName: row.lastName.trim(),
            idNumber: row.idNumber.trim(),
            password,
            currentCenter: center?.id ?? null,
            isAutoGenerated:
              !row.password?.trim() || !/^\d{5}$/.test(row.password.trim()),
          });
        });

        setCsvPreview({ valid, invalid });
      },
    });

    e.target.value = "";
  };

  // ── Handlers: bulk import
  const handleBulkImport = async () => {
    setIsImporting(true);
    try {
      const results = await runWithConcurrency(csvPreview.valid, 5, (student) =>
        addStudent({ ...student, profilePicture: null }),
      );
      const successCount = results.filter(
        (r) => r.status === "fulfilled",
      ).length;
      const failCount = results.filter((r) => r.status === "rejected").length;
      if (successCount > 0)
        toast.success(`${successCount} student(s) imported successfully.`, {
          position: "bottom-right",
        });
      if (failCount > 0)
        toast.error(`${failCount} student(s) failed to import.`);
      setCsvPreview({ valid: [], invalid: [] });
      onClose();
      onSuccess?.();
    } finally {
      setIsImporting(false);
    }
  };

  // ── Guard: modal closed
  if (!isOpen) return null;

  // ── Render
  return (
    <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50 p-4">
      <div className="bg-white dark:bg-gray-800 rounded-2xl p-8 max-w-3xl w-full shadow-2xl max-h-[90vh] scrollbar-thin scrollbar-thumb-gray overflow-y-auto">
        <div className="flex justify-between items-center mb-6">
          <h3 className="text-xl font-bold text-gray-900 dark:text-white">
            Import Preview
          </h3>
          <button
            onClick={onClose}
            className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700"
          >
            <X size={24} />
          </button>
        </div>

        {/* File upload */}
        <div className="mb-6">
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            Upload CSV File
          </label>
          <input
            type="file"
            accept=".csv"
            onChange={handleCSVUpload}
            disabled={!online}
            className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100 disabled:opacity-40 disabled:cursor-not-allowed"
          />
        </div>

        {/* Valid rows */}
        {csvPreview.valid.length > 0 && (
          <div className="mb-6">
            <h4 className="text-sm font-semibold text-green-600 dark:text-green-400 mb-3">
              ✓ {csvPreview.valid.length} student(s) ready to import
            </h4>
            <div className="border border-gray-200 dark:border-gray-700 rounded-xl overflow-hidden">
              <table className="w-full text-sm text-left">
                <thead className="bg-gray-50 dark:bg-gray-700/50">
                  <tr>
                    <th className="px-4 py-3">Name</th>
                    <th className="px-4 py-3">ID Number</th>
                    <th className="px-4 py-3">Password</th>
                    <th className="px-4 py-3">Center</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                  {csvPreview.valid.map((s, i) => (
                    <tr
                      key={i}
                      className="hover:bg-gray-50 dark:hover:bg-gray-700/50"
                    >
                      <td className="px-4 py-3">
                        {[s.firstName, s.middleName, s.lastName]
                          .filter(Boolean)
                          .join(" ")}
                      </td>
                      <td className="px-4 py-3 font-mono">{s.idNumber}</td>
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-2">
                          <span className="font-mono text-sm">
                            {s.password}
                          </span>
                          {s.isAutoGenerated && (
                            <span className="text-xs px-1.5 py-0.5 bg-blue-100 text-blue-700 rounded-full">
                              auto
                            </span>
                          )}
                          <button
                            onClick={() => {
                              navigator.clipboard.writeText(s.password);
                              toast.success("Password copied!");
                            }}
                            className="text-xs text-blue-600 hover:underline"
                          >
                            Copy
                          </button>
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        {s.currentCenter ? (
                          centers.find((c) => c.id === s.currentCenter)?.title
                        ) : (
                          <span className="italic">Not assigned</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Invalid rows */}
        {csvPreview.invalid.length > 0 && (
          <div className="mb-6">
            <h4 className="text-sm font-semibold text-red-600 dark:text-red-400 mb-3">
              {csvPreview.invalid.length} row(s) will be skipped
            </h4>
            <div className="space-y-2">
              {csvPreview.invalid.map((err, i) => (
                <div
                  key={i}
                  className="flex items-center gap-2 text-sm text-red-600 bg-red-50 dark:bg-red-900/20 px-4 py-2 rounded-lg"
                >
                  <span className="font-medium">Row {err.row}:</span>{" "}
                  {err.reason}
                </div>
              ))}
            </div>
          </div>
        )}

        {csvPreview.valid.length === 0 && csvPreview.invalid.length === 0 && (
          <p className="text-center text-gray-500 py-8">
            Upload a CSV file to see preview.
          </p>
        )}

        <div className="flex gap-4 mt-6">
          {csvPreview.valid.length > 0 && (
            <button
              onClick={handleBulkImport}
              disabled={isImporting || !online}
              className="flex-1 bg-green-600 hover:bg-green-700 disabled:opacity-50 text-white py-3 px-6 rounded-xl font-medium"
            >
              {isImporting
                ? "Importing..."
                : `Import ${csvPreview.valid.length} Student(s)`}
            </button>
          )}
          <button
            onClick={onClose}
            className="flex-1 bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 text-gray-900 dark:text-gray-100 py-3 px-6 rounded-xl font-medium"
          >
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
}
